### ISSUE TITLE
Blank Screen On Clover Boot & hang at +++++++

### ISSUE THREAD

**Issue by puste1980** [SkyrilHD/Dell-E7250-Hackintosh#3] opened 2020-04-18 01:18 UTC
hi,
I created the boot drive, substituted the EFI folder in the EFI volume with yours, and boot up. The boot starts but the page shows the only grey color and the Clover green logo...no options.
What can be?
thanks
A

**Comment by SkyrilHD** [comment] 2020-04-18 10:33
Hi,
can you press F3 to show hidden entries? Can you go while you are in the Clover menu to the settings? I also attached a config.plist file where FastBoot is disabled. (But I don't think this changes too much)

[config.plist.zip](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/4496456/config.plist.zip)

**Comment by puste1980** [comment] 2020-04-18 13:44
Thanks Man!
Unfortunately, the situation improved and I can see the options, but there is no icon for the Catalina Boot to run…
Sorry, man, this is the first time for me, it’s really frustrating. I spend all day yesterday..
I tried though to use UniBeast without changing the EFI folder, and that went better then others, but still got stuck in the middle of the process with many system lines and not moving ahead after a while. Waited for 1hour but it was stuck…

**Comment by SkyrilHD** [comment] 2020-04-18 13:47
Can you boot with verbose mode and maybe send a picture where it hangs?

**Comment by puste1980** [comment] 2020-04-18 14:10
I will thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by puste1980** [comment] 2020-04-18 14:37
I will try both (with and without your EFI+newplist)
Give me sometime and I will send you screenshots
Thanks dude!

**Comment by puste1980** [comment] 2020-04-18 14:58
[Image.jpeg]

Hi, this is with standard UNibease and UEFI Catalina.
I will send your version ASAP

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by puste1980** [comment] 2020-04-18 15:31
Is giving me error because images are too large, what is the min size?
Thanks
A

**Comment by puste1980** [comment] 2020-04-18 15:33
[Image.jpeg]

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by puste1980** [comment] 2020-04-18 15:34
This was with your EFI plus this AM plist file

From: _______ <_______@gmail.com>
Date: Saturday, April 18, 2020 at 11:33 AM
To: SkyrilHD/Dell-E7250-Hackintosh <reply@reply.github.com>, SkyrilHD/Dell-E7250-Hackintosh <Dell-E7250-Hackintosh@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [SkyrilHD/Dell-E7250-Hackintosh] Blank Screen On Clover Boot (#3)

[Image.jpeg]

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SkyrilHD** [comment] 2020-04-18 15:35
I can only see Image.jpeg but not the actual image

Also I noticed that your email was visible, so I edited that out.

**Comment by SkyrilHD** [comment] 2020-04-18 21:17
Any update?

**Comment by puste1980** [comment] 2020-04-18 22:05
I am stuck..where can I load pictures?

Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by SkyrilHD** [comment] 2020-04-18 22:19
Have you tried imgur?

**Comment by puste1980** [comment] 2020-04-18 22:36
I will right away

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by puste1980** [comment] 2020-04-18 22:39
0757 is the standard EFI config
0758 is the EFI modified with this AM plist file

![IMG_0757](https://user-images.githubusercontent.com/48568503/79672917-fa775b80-81a3-11ea-8eac-fcdfc53a2f7e.jpg)
![IMG_0758](https://user-images.githubusercontent.com/48568503/79672920-fcd9b580-81a3-11ea-8752-193028a42b37.jpg)

**Comment by puste1980** [comment] 2020-04-18 22:44
I am also trying to reinstall win10 standard, in order to have a "normal situatiion" on the machine..dont' know if could help...

**Comment by SkyrilHD** [comment] 2020-04-18 22:46
1. Try renaming the 10.15 folder in the kexts folder to Other

If this still doesn't work, then try deleting USBInjectAll.kext

**Comment by puste1980** [comment] 2020-04-18 23:15
with which config? standard EFI? your EFI v1 ? or v2 with new plist?

**Comment by SkyrilHD** [comment] 2020-04-18 23:21
Both please.

The installer is on the USB stick right?

**Comment by puste1980** [comment] 2020-04-18 23:21
Yes

**Comment by puste1980** [comment] 2020-04-18 23:21
I will work on it, keep you posted

**Comment by puste1980** [comment] 2020-04-18 23:51
tried all options, renaming kexts to Other, deleting the file, using plist of this AM, this is what I get, a menu with "Boot with Windows from EFI.."

here is the picture
![IMG_0760](https://user-images.githubusercontent.com/48568503/79674100-0b2ccf00-81ae-11ea-8014-f1c024530e5f.jpg)

**Comment by SkyrilHD** [comment] 2020-04-19 00:21
Ok, apparently the HFS+ driver isn't working, so here is the replacement...

Copy the .efi to drivers/UEFI folder


[HFSPlus-64.efi.zip](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/4498100/HFSPlus-64.efi.zip)

**Comment by puste1980** [comment] 2020-04-19 02:04
Installation started again, but it got stuck to the same point with lots of ++++++++++++++++++

**Comment by puste1980** [comment] 2020-04-19 02:04
I will leave it there for a while

**Comment by SkyrilHD** [comment] 2020-04-19 10:23
Can you add USBInjectAll.kext back?

Also is it a USB3 Flash drive?

**Comment by SkyrilHD** [comment] 2020-04-19 11:40
So, I made a Installer Disk too and got the same error as you...

Now, I made some changes in the config.plist file and updated Clover to its latest version.

Follow these steps and you should get Installer working:

(Remove old stuff)
Delete the APPLE folder in EFI/

(Update Clover)
Copy BOOTX64.efi to EFI/BOOT/
Copy CLOVERX64.efi to EFI/COLVER/

(Update some stuff)
Replace the config.plist with the old one
Copy the SSDT-EC.dsl to EFI/CLOVER/ACPI/patched/
Copy HFSPlus-64.efi to EFI/CLOVER/drivers/UEFI/
Rename the 10.15 folder in EFI/CLOVER/kexts/ to Other

[Update.zip](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/4498876/Update.zip)

Hope this works to you :)

**Comment by puste1980** [comment] 2020-04-19 12:11
yes, it is a USB3 SanDisk.
I try and let you know, thanks for the hard work!

**Comment by puste1980** [comment] 2020-04-19 12:46
I am installing finally, Thanks!

**Comment by puste1980** [comment] 2020-04-19 13:29
Hi, I finished installing everything and as anticipated wifi does not work. So I go ahead, buy a W.2, install it, copy the ktext to the ktext/Other folder and that's it? thanks for all your help, great job!

**Comment by SkyrilHD** [comment] 2020-04-19 13:35
Great to hear that everything works...

You need a suitable card with M.2 2230 slot (key A/E). Some card will work out of the box, some need a kext to have working WiFi. May need a little research on the internet.

If the issue is done, please close the issue... Thanks

**Closed as completed** 2020-04-19 13:36 UTC
Labels: bug
